module.exports = {
    START:0,
    USER_STATUS:1,
    MARK_POSITION:2,
    HEAL:3,
    USER_LEVEL_INFO:4,
    LEVEL_UP : 5,
    ALLOC_POTENTIAL: 6,
    INIT_ROLE_TYPE: 7,
    QUERY_HEAL_CONFIG:8,
    QUERY_ROLE_TYPE_CONFIG:9,
    QUERY_OTHER_USER_INFO:10,

    QUERY_EQUIPMENT_LIST:100,
    BUY_EQUIPMENT:101,
    EQUIP :102,
    STRENGTHEN:103,
    GET_EQUIPMENT_IN_BAG:104,
    QUERY_STRENGTHEN_CONFIG:105,

    QUERY_SKILL_LIST:200,
    QUERY_UPSKILL_CONFIG:201,
    UPSKILL:202,

    FIGHT:300,
};