module.exports = {
    START:0,
    USER_STATUS:1,
    MARK_POSITION:2,
    HEAL:3,
    USER_LEVEL_INFO:4,
    LEVEL_UP : 5,
    ALLOC_POTENTIAL: 6,
    INIT_ROLE_TYPE: 7,

    QUERY_EQUIPMENT_LIST:100,
    BUY_EQUIPMENT:101,
};