module.exports = {
    SWORD_OF_5:{
        TYPE:0,
        ATK:5,
        LEVEL:5,
        VALUE:5,
    },
    SWORD_OF_15:{
        TYPE:0,
        ATK:15,
        LEVEL:15,
        VALUE:20,
    },
    SWORD_OF_25:{
        TYPE:0,
        ATK:40,
        LEVEL:25,
        VALUE:50
    },
    SWORD_OF_35:{
        TYPE:0,
        ATK:100,
        LEVEL:35,
        VALUE:200
    },
    SWORD_OF_45:{
        TYPE:0,
        ATK:200,
        LEVEL:45,
        VALUE:1000
    },
};