module.exports = {
    SWORD_OF_5:{
        TEMPLATE_ID:0,
        ATK:5,
        VALUE:5
    },
    SWORD_OF_15:{
        TEMPLATE_ID:1,
        ATK:15,
        VALUE:20
    },
    SWORD_OF_25:{
        TEMPLATE_ID:2,
        ATK:40,
        VALUE:50
    },
    SWORD_OF_35:{
        TEMPLATE_ID:3,
        ATK:100,
        VALUE:200
    },
    SWORD_OF_45:{
        TEMPLATE_ID:4,
        ATK:200,
        VALUE:1000
    },
};