module.exports = {
    0:{
        NAME:'野猪',
        ATK:5,
        DEF:5,
        SKILLS:{
            ATTACK:{
                level:1
            }
        },
        EXP:1,
        GOLD:1,
        MAX_HP:15,
        MAX_MP:0
    },
    1:{
        NAME:'强盗',
        ATK:10,
        DEF:10,
        SKILLS:{
            ATTACK:{
                level:1
            }
        },
        EXP:3,
        GOLD:3,
        MAX_HP:20,
        MAX_MP:0
    },
    2:{
        NAME:'狼',
        ATK:20,
        DEF:20,
        SKILLS:{
            ATTACK:{
                level:1
            }
        },
        EXP:10,
        GOLD:10,
        MAX_HP:30,
        MAX_MP:0
    },
    3:{
        NAME:'黑熊精',
        ATK:50,
        DEF:50,
        SKILLS:{
            ATTACK:{
                level:1
            }
        },
        EXP:20,
        GOLD:20,
        MAX_HP:70,
        MAX_MP:0
    },

};