
module.exports = {
    ATTACK:{
        NAME:'普通攻击',
        ATK_COEFFICIENT:{
            1:1,
            2:1.05,
            3:1.1,
            4:1.15,
            5:1.2
        },
        DESCRIPTION:'造成基于攻击力的加成伤害',
        MAGIC_COST:0,
        DEF_IGNORE:0,
        KEY:'ATTACK'
    },
    DASH:{
        NAME:'冲刺',
        ATK_COEFFICIENT:{
            1:1.2,
            2:1.3,
            3:1.4,
            4:1.5,
            5:1.6
        },
        DESCRIPTION:'造成基于攻击力的加成伤害',
        MAGIC_COST:3,
        DEF_IGNORE:0.1,
        KEY:'DASH'
    },
    FIRE_BALL:{
        NAME:'火球术',
        MAGIC_COEFFICIENT:{
            1:1.2,
            2:1.3,
            3:1.4,
            4:1.5,
            5:1.6
        },
        DESCRIPTION:'造成基于法力值的加成伤害',
        MAGIC_COST:5,
        DEF_IGNORE:0.2,
        KEY:'FIRE_BALL'
    },
    PRAY:{
        NAME:'祈祷',
        DEF_COEFFICIENT:{
            1:-1.2,
            2:-1.3,
            3:-1.4,
            4:-1.5,
            5:-1.6
        },
        DESCRIPTION:'产生基于防御值的治疗效果',
        MAGIC_COST:4,
        DEF_IGNORE:1,
        KEY:'PRAY'
    },
};